# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    environment: release

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: setup node
        uses: actions/setup-node@v4
        with:
          cache: 'npm'
          node-version: 20

      - name: install dependencies
        run: npm install

      - name: build
        run: npm run build
      
      - name: release
        run: npm run release
        env:
          NPM_AUTH_TOKEN: ${{ vars.NPM_TOKEN }}
